# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/silvio/Pynq/Ultra96/grayscale-accel/Vivado Project/GrayScale.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_1_0/design_1_axis_dwidth_converter_1_0.xci
# IP: The module: 'design_1_axis_dwidth_converter_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/silvio/Pynq/Ultra96/grayscale-accel/Vivado Project/GrayScale.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_1_0/design_1_axis_dwidth_converter_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_dwidth_converter_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/silvio/Pynq/Ultra96/grayscale-accel/Vivado Project/GrayScale.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_1_0/design_1_axis_dwidth_converter_1_0.xci
# IP: The module: 'design_1_axis_dwidth_converter_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/silvio/Pynq/Ultra96/grayscale-accel/Vivado Project/GrayScale.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_1_0/design_1_axis_dwidth_converter_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_dwidth_converter_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
